#!/usr/bin/env bash
# Cross-compile smoke matrix: every target supported by the three SDKs.
# Each target is built into `smoke/`; failures are accumulated across targets
# and the script exits non-zero if any of them failed.
# Per-target output is streamed to the job log AND saved to smoke-<target>.log
# so the final summary can show a tail of each failing build.
set -u
set -o pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT/tests/smoke"

failed=""
run_target() {
  local name="$1"
  shift
  echo ""
  echo "===== $name ====="
  rm -rf zig-out
  local logfile="${ROOT}/smoke-${name}.log"
  if ! zig build "$@" 2>&1 | tee "$logfile"; then
    echo "FAILED: $name"
    failed="$failed $name"
  else
    echo "OK: $name"
  fi
}

# Android (NDK r29: its max API is 35, every arch ships API dirs 21-35 and
# riscv64 only the max. Other NDK releases support a different max API --
# r30-beta2: 36, r30-beta3: 37 -- so use the API level the pinned NDK
# supports; cross has no hardcoded API rule, the directory check adapts.)
for t in \
  aarch64-linux-android.35 \
  arm-linux-androideabi.35 \
  x86_64-linux-android.35 \
  x86-linux-android.35 \
  riscv64-linux-android.35 \
; do
  run_target "$t" "-Dtarget=$t"
done

# OpenHarmony (zig does not support the .ohos ABI yet: use the musl ABI plus
# -Dohos=true so the OHOS NDK sysroot is used).
for t in \
  aarch64-linux-musl \
  arm-linux-musleabihf \
  x86_64-linux-musl \
; do
  run_target "ohos-$t" "-Dtarget=$t" -Dohos=true
done

# Emscripten (cache sysroots are generated by the workflow beforehand)
for t in wasm32-emscripten wasm64-emscripten; do
  run_target "$t" "-Dtarget=$t"
done

if [ -n "$failed" ]; then
  echo ""
  echo "FAILED targets:"
  for t in $failed; do
    echo "  - $t"
    echo "    --- last output of smoke-${t}.log ---"
    tail -n 20 "${ROOT}/smoke-${t}.log" 2>/dev/null | sed 's/^/    /'
  done
  exit 1
fi

echo ""
echo "ALL TARGETS OK"
